import { Container } from "react-bootstrap";
import Footer from "./components/footer";
import NavBar from "./components/navbar";

export default function Produtos() {
    return (
        <div>
            <NavBar />
            <Container className="conteudo">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi iure pariatur aspernatur laboriosam numquam vitae odit! Vitae, quasi mollitia commodi, laboriosam excepturi reiciendis est hic amet quam, cum sunt. Facilis, vitae earum saepe quos natus dolores non numquam magnam rem repellat modi maxime voluptatibus veritatis aperiam iusto rerum consequatur molestias, atque dolorem? Voluptas expedita voluptates vel quod nulla consectetur doloremque totam illum iste illo. Iure, voluptas. Deleniti minima pariatur voluptatibus dolorum eveniet, cum repudiandae laborum ipsam ex voluptatem cumque necessitatibus distinctio iure odio dolore! In veritatis recusandae velit dicta numquam! Repellat eaque quaerat fuga dolore rem, amet ut id incidunt perferendis sunt maiores ipsum labore, voluptatibus sed sapiente corporis. Dolores illum voluptatibus iste asperiores corrupti in temporibus nulla incidunt pariatur commodi dolorem nam nisi labore ducimus autem, possimus officiis ipsam, facere sint quas, qui sed harum similique cum. In, necessitatibus saepe natus, deserunt doloribus cum laboriosam, totam consequatur cupiditate corporis obcaecati velit nulla commodi autem enim dolore blanditiis odit ab. Nesciunt aliquam consectetur, esse quam laboriosam quae dolore! Cumque laudantium quidem impedit delectus cupiditate facere a ratione vero assumenda alias autem vel, enim tenetur! Impedit, dolorum numquam, quis praesentium ad cupiditate non voluptatum, iure distinctio atque esse exercitationem totam eum.</p>
                <p>Soluta, consectetur blanditiis vel mollitia sequi recusandae aliquid sapiente ea fugit consequatur, perspiciatis quisquam. Molestiae dolorem reprehenderit, nulla ab totam minima accusantium dignissimos velit. Ducimus sint nesciunt ex dolore quod rerum modi, voluptatum ullam minus deserunt eaque natus. Facere omnis in cum adipisci fugiat corporis possimus dignissimos est inventore reiciendis cumque labore voluptates dolore excepturi, quas ab doloribus quo accusantium, blanditiis sint saepe at, quam vitae explicabo! Consequuntur perspiciatis unde soluta facere illo iure impedit fuga assumenda excepturi quis ut similique error culpa eaque voluptate aliquam minima, porro tenetur quas necessitatibus fugiat quibusdam veritatis, temporibus perferendis. Ducimus odit, voluptas consequatur illo autem, similique facilis vero, quaerat blanditiis minima quasi. Reiciendis deserunt iure quos corporis illo atque tenetur eaque labore doloribus quisquam nostrum adipisci voluptate non id, quis exercitationem eos itaque porro vel odit culpa? Harum beatae animi, rem quod dolores, fugiat quis odit iusto culpa soluta debitis doloremque alias aliquid minima tempora quidem voluptatibus odio exercitationem assumenda aspernatur veritatis suscipit amet rerum. Officiis, vero placeat unde obcaecati molestiae vel culpa enim, nesciunt aperiam qui deserunt necessitatibus in dolorum. Excepturi, illo ullam? Nesciunt natus, perspiciatis provident totam eligendi veniam dolorum harum optio mollitia et dolorem doloremque delectus voluptatem consequatur nam voluptate.</p>
                <p>Praesentium necessitatibus obcaecati nihil sint ullam, molestias velit! Mollitia enim adipisci eum, corporis ex corrupti ratione, beatae maxime repellat soluta perferendis, neque dignissimos illum temporibus voluptatum! Magni, libero cum. Laudantium culpa laborum officiis expedita quibusdam accusantium minus dolor nam sunt optio? At velit commodi dolorem veniam id esse, corporis porro ullam voluptates sint perspiciatis rem perferendis illum sit sed veritatis temporibus quisquam, blanditiis expedita. Veritatis eaque earum nostrum sint consequuntur minima quam aut, velit voluptatum repudiandae quas rerum quibusdam tempore deleniti officia assumenda neque at tenetur, nisi beatae sapiente repellat. Inventore nulla voluptate, quidem dignissimos magnam vel ex laudantium quos, consectetur dolore consequuntur vitae illum magni suscipit assumenda perspiciatis quam. Iure cumque, mollitia molestias assumenda omnis esse voluptas molestiae maiores corrupti ullam necessitatibus quasi? Deserunt iure eaque ipsum distinctio sequi voluptates consectetur quis laudantium obcaecati necessitatibus. Minus quas necessitatibus corporis incidunt deleniti nisi, enim adipisci saepe distinctio reprehenderit dicta labore velit explicabo! Corrupti quasi inventore distinctio placeat repellat laborum reprehenderit! Quam officiis voluptate quasi dolorem facere exercitationem libero in hic, sequi voluptatum veritatis. Dolor eum, corporis repellat asperiores consequuntur alias quam saepe dolorem accusantium cumque ea voluptatum molestiae illo architecto a libero? Unde quaerat expedita quos, inventore eaque odit quis?</p>
            </Container>
            <Footer />
        </div>
    )

}